use CCP
truncate table provision_toa

insert into provision_toa ([Técnico],
	[ID RECURSO],
	[Subtipo de Actividad],
	[Código de actuación],
	[Número de Petición],
	[Número de Orden],
	[Empresa],
	[Fecha de Emisión/Reclamo],
	[Intervalo de tiempo],
	[Central_Manzana],
	Central,
	[Segmento del cliente],
	[Nombre],
	[Telefono Contacto 1],
	[Número Teléfono],
	[Tiempo de Viaje],
	[Duración de la actividad],
	[Habilidad del trabajo],
	[Estado de la orden],
	[Pendiente instancia externa],
	[Tecnologia Voz],
	[Tecnologia Banda Ancha],
	[Tecnologia TV],
	[Multiproducto],
	[Tipo de Acceso],
	[Tipo de Terminación],
	[Garantía],
	[Zona Peligrosa],
	[Fecha de Cita Original],
	[Bucket Inicial],
	[Manzana],
	[Razon de Suspension Instalacion],
	[Motivo no realizado instalación],
	[A_SLOW_NAVIGATION],
	[A_VOIP_NOT_WORKING],
	[Fecha/Hora de autorizacion del cierre],
	[Fecha/Hora de autorizacion de la suspension],
	[Usuario que autorizo la suspension],
	[Fecha/Hora de autorizacion del quiebre],
	[Access ID],
	[Recordatorio Realizado],
	[Respuesta del Cliente],
	[Tipo de cliente],
	[Subtipo de cliente],
	[Fecha creacion toa],
	Programacion,
	Actualizacion
)

select LEFT ([Técnico], 100) as Tecno,
	case when ISNUMERIC ([ID RECURSO]) = 0 then null else [ID RECURSO] end as ID_RECURSO,
	LEFT ([Subtipo de Actividad],80) as [Subtipo Actividad],
	LEFT ([Código de actuación],80) as [Cod Actuacion],
	LEFT ([Número de Petición],50) as Peticion,
	LEFT ([Número de Orden],50) as Orden,
	LEFT ([Empresa],50) as Empresa,
	cast ([Fecha de Emisión Reclamo] as date) as [Fecha Emision],
	LEFT ([Intervalo de tiempo],10) as Intervalo,
	LEFT ([Central_Manzana],12) as [Ctral Manzana],
	SUBSTRING(Central_Manzana,0,CHARINDEX('_', Central_Manzana)) as Central,
	LEFT ([Segmento del cliente],20) as Segmento,
	LEFT ([Nombre],120) as Nombre,
	LEFT ([Telefono Contacto 1],15) as Tel_contacto1,
	LEFT ([Número Teléfono],15) as Telefono,
	LEFT ([Tiempo de Viaje],8) as [Tiempo Viaje],
	LEFT ([Duración de la actividad],8) as [Dura Actividad],
	LEFT ([Habilidad de trabajo],120) as Habilidad,
	LEFT ([Estado de la orden],25) as [Estado Orden],
	LEFT ([Pendiente instancia externa],80) as [Pend Inst Externa],
	LEFT ([Tecnologia Voz],20) as Voz,
	LEFT ([Tecnologia Banda Ancha],20) as Banda,
	LEFT ([Tecnologia TV],20) as TV,
	LEFT ([Multiproducto],50) as Multiproducto,
	LEFT (tecnologia,25) as Tecnologia,--LEFT ([Tipo de Acceso], 10)
	LEFT ([Tipo de Terminación],25) as Terminacion,
	case when [Garantía] = 'sÃ­' then 'sí' else [Garantía] end as Garantia,
	LEFT ([Zona Peligrosa],3) as ZP,
	cast ([Fecha de Cita Original] as date) as [Fecha cita origi],
	LEFT ([Bucket Inicial],80) as Bucket,
	case when ISNUMERIC ([Manzana]) = 0 then 0 else [Manzana] end as Manzana,
	LEFT ([Razon de Suspension Instalacion],100) as [Razon Suspension],
	LEFT ([Motivo no realizado instalación],150) as [Motivo No Realizado],
	LEFT ([A_SLOW_NAVIGATION],3) as SLOW_NAVIGATION,
	LEFT ([A_VOIP_NOT_WORKING],3) as VOIP_NOT_WORKING,
	case when TIMESTAMP = '' then null
			else cast(TIMESTAMP as smalldatetime) end  as [F autoriza Cierre],
	case when [Fecha/Hora de autorizacion de la suspension] = '1899-12-30 00:00:00.000' then null
			else cast ([Fecha/Hora de autorizacion de la suspension] as smalldatetime) end  as [F autoriza Suspension],
	[Usuario que autorizo la suspension],
	case when [Fecha/Hora de autorizacion del quiebre] = '1899-12-30 00:00:00.000' then null
			else cast ([Fecha/Hora de autorizacion del quiebre] as smalldatetime) end  as [F autoriza quiebre],
	case when ISNUMERIC ([Access ID]) = 0 then null else [Access ID] end as Access,
	LEFT ([Recordatorio Realizado], 3),
	LEFT ([Respuesta del Cliente], 10),
	LEFT ([Tipo de cliente], 50),
	LEFT ([Subtipo de cliente], 50),
	cast ([Fecha Ingreso TOA] as smalldatetime) as [Fecha Ingr TOA],
	'PROGRAMADO',
	cast (timestamp as smalldatetime)

from [10.249.15.194\DATAFLOW].ATC.dbo.toa_primera
where CAST (timestamp as DATE) = CAST (getdate() as DATE)