use CCP
--set dateformat 'dmy'

update provision_toa_bk
set [Enrutado automático a fecha] = ''
where [Enrutado automático a fecha] = '-'

update provision_toa_bk
set [Fecha de Cita] = ''
where [Fecha de Cita] = '-'

update provision_toa_bk
set [Fecha Ingreso TOA] = ''
where [Fecha Ingreso TOA] = '-'

update provision_toa_bk
set [Fecha de Emisión/Reclamo] = ''
where [Fecha de Emisión/Reclamo] = '-'

insert into provision_toa ([Técnico],
	[ID RECURSO],
	[Subtipo de Actividad],
	[Código de actuación],
	[Número de Petición],
	[Número de Orden],
	[Empresa],
	[Fecha de Emisión/Reclamo],
	[Intervalo de tiempo],
	[SLA Inicio],
	[SLA Fin],
	[Ciudad],
	[Dirección],
	[Dirección (componente vertical)],
	[Direccion Polar X],
	[Direccion Polar Y],
	[Central_Manzana],
	[Zona de Trabajo],
	[Segmento del cliente],
	[Nombre],
	[Telefono Contacto 1],
	[Telefono Contacto 2],
	[Número Teléfono],
	[Tiempo de Viaje],
	[Duración de la actividad],
	[Habilidad del trabajo],
	[Estado de la orden],
	[Pendiente instancia externa],
	[Categoría de Capacidad],
	[Tecnologia Voz],
	[Tecnologia Banda Ancha],
	[Tecnologia TV],
	[Multiproducto],
	[Tipo de Acceso],
	[Tipo Equipo de Acceso],
	[Tipo de Terminación],
	[Síntoma],
	[Diagnóstico Inicial],
	[Diagnóstico Actual],
	[Repetido],
	[Garantía],
	[Validación técnica],
	[Rural],
	[Zona Peligrosa],
	[Cable Primario],
	[Par Primario],
	[Par Secundario],
	[Pin ADSL],
	[Bloque ADSL],
	[Número de equipo de PI],
	[Armario],
	[Nivel de Urgencia (Prioridad)],
	[Prioridad],
	[Central],
	[Nombre Central],
	[Fecha de Cita Original],
	[Bucket Inicial],
	[Reitero_48HS],
	[Cuadrante],
	[Manzana],
	[Ventana de servicio],
	[Ventana de Llegada],
	[Correo electronico],
	[Crónico],
	[Desviado],
	[Ubicacion],
	[Enrutado automático a fecha],
	[Cita ID],
	[Razon de Suspension Instalacion],
	[Motivo no realizado instalación],
	[Comentarios Tecnico],
	[A_SLOW_NAVIGATION],
	[A_VOIP_NOT_WORKING],
	[Primera operación manual],
	[Distancia a la Ubicacion mas cercana],
	[Primera operación manual realizada por usuario],
	[Usuario que autorizo el cierre],
	[Fecha/Hora de autorizacion del cierre],
	[Fecha/Hora de autorizacion de la suspension],
	[Usuario que autorizo la suspension#],
	[Fecha/Hora de autorizacion del quiebre],
	[Usuario que Autoriza Informar],
	[Access ID],
	[Recordatorio Realizado],
	[Respuesta del Cliente],
	[Fecha de respuesta del cliente],
	[Cita al ingreso],
	[Tipo de cliente],
	[Subtipo de cliente],
	Programacion,
	Actualizacion,
	[Fecha creacion toa]
)

select LEFT ([Técnico], 100),
	case when ISNUMERIC ([ID RECURSO]) = 0 then null else LEFT ([ID RECURSO], 5) end as ID_RECURSO,
	LEFT ([Subtipo de Actividad], 80) as Subtipo_actividad,
	LEFT ([Código de actuación], 80) as Cod_actuacion,
	LEFT ([Número de Petición], 50) as Peticion,
	LEFT ([Número de Orden], 50) as Orden,
	LEFT ([Empresa], 50) as Empresa,
	case when [Fecha de Emisión/Reclamo] = '' then null else cast ([Fecha de Emisión/Reclamo] as date) end as f_emison_recl,
	LEFT ([Intervalo de tiempo], 10) as Intervalo_tiempo,
	convert (date, (LEFT ([SLA Inicio],8)), 3) as sla_ini,
    convert (date, (LEFT ([SLA Fin],8)), 3) as sla_fini,
	LEFT ([Ciudad], 100) as Ciudad,
	[Dirección],
	[Dirección (componente vertical)],
	LEFT ([Direccion Polar X], 30) as Direccion_Polar_X,
	LEFT ([Direccion Polar Y], 30) as Direccion_Polar_Y,
	LEFT ([Central_Manzana], 12) as Central_Mzna,
	LEFT ([Zona de Trabajo], 150) as Zona_Trabajo,
	LEFT ([Segmento del cliente], 20) as Seg_cliente,
	LEFT ([Nombre], 120),
	LEFT ([Telefono Contacto 1], 15),
	LEFT ([Telefono Contacto 2], 15),
	LEFT ([Número Teléfono], 15),
	LEFT ([Tiempo de Viaje], 8),
	LEFT ([Duración de la actividad], 8),
	LEFT ([Habilidad del trabajo], 120),
	LEFT ([Estado de la orden], 25),
	LEFT ([Pendiente instancia externa], 80),
	LEFT ([Categoría de Capacidad], 100),
	LEFT ([Tecnologia Voz], 20),
	LEFT ([Tecnologia Banda Ancha], 20),
	LEFT ([Tecnologia TV], 20),
	LEFT ([Multiproducto], 50),
	LEFT ([Tipo de Acceso], 10),
	LEFT ([Tipo Equipo de Acceso], 25),
	LEFT ([Tipo de Terminación], 25),
	LEFT ([Síntoma], 80),
	LEFT ([Diagnóstico Inicial], 100),
	LEFT ([Diagnóstico Actual], 80),
	LEFT ([Repetido], 2),
	LEFT ([Garantía], 3),
	LEFT ([Validación técnica], 3),
	LEFT ([Rural], 3),
	LEFT ([Zona Peligrosa], 3),
	case when ISNUMERIC ([Cable Primario]) = 0 then null else LEFT ([Cable Primario], 5) end,
	case when ISNUMERIC ([Par Primario]) = 0 then null else LEFT ([Par Primario], 5) end,
	case when ISNUMERIC ([Par Secundario]) = 0 then null else LEFT ([Par Secundario], 5) end,
	case when ISNUMERIC ([Pin ADSL]) = 0 then null else LEFT ([Pin ADSL], 3) end,
	LEFT ([Bloque ADSL], 8),
	LEFT ([Número de equipo de PI], 15),
	LEFT ([Armario], 15),
	LEFT ([Nivel de Urgencia (Prioridad)], 3),
	case when ISNUMERIC ([Prioridad]) = 0 then null else LEFT ([Prioridad], 3) end,
	case when ISNUMERIC ([Central]) = 0 then null else LEFT ([Central], 5) end,
	LEFT ([Nombre Central], 50),
	case when [Fecha de Cita Original] = '' then null else REPLACE ([Fecha de Cita Original], '-', '') end,
	LEFT ([Bucket Inicial], 80),
	LEFT ([Reitero_48HS], 3),
	LEFT ([Cuadrante], 15),
	case when ISNUMERIC ([Manzana]) = 0 then null else LEFT ([Manzana], 5) end,
	LEFT ([Ventana de servicio], 10),
	LEFT ([Ventana de Llegada], 10),
	LEFT ([Correo electronico], 150),
	LEFT ([Crónico], 3),
	LEFT ([Desviado], 3),
	LEFT ([Ubicacion], 50),
	case when [Enrutado automático a fecha] = '' then null else '20' + RIGHT ([Enrutado automático a fecha], 2) + '-' + SUBSTRING ([Enrutado automático a fecha], 4, 2) + '-' + LEFT ([Enrutado automático a fecha], 2)  end as [Enrutado auto],
	case when ISNUMERIC ([Cita ID]) = 0 then null else LEFT ([Cita ID], 8) end,
	LEFT ([Razon de Suspension Instalacion], 100),
	LEFT ([Motivo no realizado instalación], 150),
	[Comentarios Tecnico],
	LEFT ([A_SLOW_NAVIGATION], 3),
	LEFT ([A_VOIP_NOT_WORKING], 3),
	LEFT ([Primera operación manual], 80),
	case when ISNUMERIC ([Distancia a la Ubicacion mas cercana]) = 0 or [Distancia a la Ubicacion mas cercana] > 32000 then null else LEFT ([Distancia a la Ubicacion mas cercana], 5) end,
	case when ISNUMERIC ([Primera operación manual realizada por usuario]) = 0 then null else LEFT ([Primera operación manual realizada por usuario], 5) end,
	LEFT ([Usuario que autorizo el cierre], 100),
	case when [Fecha/Hora de autorizacion del cierre] = '' OR [Fecha/Hora de autorizacion del cierre] not like '2%' then null else [Fecha/Hora de autorizacion del cierre] end,
	case when [Fecha/Hora de autorizacion de la suspension] = '' OR [Fecha/Hora de autorizacion de la suspension] not like '2%' then null else [Fecha/Hora de autorizacion de la suspension] end,
	LEFT ([Usuario que autorizo la suspension#], 15),
	case when [Fecha/Hora de autorizacion del quiebre] = '' then null else [Fecha/Hora de autorizacion del quiebre] end,
	LEFT ([Usuario que Autoriza Informar], 150),
	LEFT ([Access ID], 25),
	LEFT ([Recordatorio Realizado], 3),
	LEFT ([Respuesta del Cliente], 10),
	case when [Fecha de respuesta del cliente] = '' then null else [Fecha de respuesta del cliente] end,
	case when [Cita al ingreso] = '' then null else [Cita al ingreso] end,
	LEFT ([Tipo de cliente], 50),
	LEFT ([Subtipo de cliente], 50),
	'NO PROGRAMADO',
	cast (getdate() as smalldatetime),
	[Fecha Ingreso TOA]

from provision_toa_bk