delete from [10.244.89.164].TELEGESTION.dbo.av_averias

insert into [10.244.89.164].TELEGESTION.dbo.av_averias ([Técnico]
      ,[ID RECURSO]
      ,[Subtipo de Actividad]
      ,[Código de actuación]
      ,[Número de Petición]
      ,[Número de Orden]
      ,[Empresa]
      ,[Fecha de Emisión/Reclamo]
      ,[Estado de la orden]
      ,[Categoría de Capacidad]
      ,[Tecnologia Voz]
      ,[Tecnologia Banda Ancha]
      ,[Tecnologia TV]
      ,[Multiproducto]
      ,[Tipo de Acceso]
      ,[Tipo Equipo de Acceso]
      ,[Síntoma]
      ,[Diagnóstico Inicial]
      ,[Diagnóstico Actual]
      ,[Garantía]
      ,[Central]
      ,[Nombre Central]
      ,[Bucket Inicial]
      ,[Razon de Suspension Instalacion]
      ,[Motivo no realizado instalación]
      ,[Comentarios Tecnico]
      ,[Usuario que autorizo el cierre]
      ,[Fecha/Hora de autorizacion del cierre]
      ,[Fecha/Hora de autorizacion de la suspension]
      ,[Usuario que autorizo la suspension#]
      ,[Fecha/Hora de autorizacion del quiebre]
      ,[Usuario que Autoriza Informar]
      ,[Access ID]
      ,[Tipo de cliente]
      ,[Subtipo de cliente]
      ,[Programacion]
      ,[Fecha_de_actualizacion]
      ,[Fecha creación TOA])
      
 select [Técnico]
      ,[ID RECURSO]
      ,[Subtipo de Actividad]
      ,[Código de actuación]
      ,[Número de Petición]
      ,[Número de Orden]
      ,[Empresa]
      ,[Fecha de Emisión/Reclamo]
      ,[Estado de la orden]
      ,[Categoría de Capacidad]
      ,[Tecnologia Voz]
      ,[Tecnologia Banda Ancha]
      ,[Tecnologia TV]
      ,[Multiproducto]
      ,[Tipo de Acceso]
      ,[Tipo Equipo de Acceso]
      ,[Síntoma]
      ,[Diagnóstico Inicial]
      ,[Diagnóstico Actual]
      ,[Garantía]
      ,[Central]
      ,[Nombre Central]
      ,[Bucket Inicial]
      ,[Razon de Suspension Instalacion]
      ,[Motivo no realizado instalación]
      ,[Comentarios Tecnico]
      ,[Usuario que autorizo el cierre]
      ,[Fecha/Hora de autorizacion del cierre]
      ,[Fecha/Hora de autorizacion de la suspension]
      ,[Usuario que autorizo la suspension]
      ,[Fecha/Hora de autorizacion del quiebre]
      ,[Usuario que Autoriza Informar]
      ,[Access ID]
      ,[Tipo de cliente]
      ,[Subtipo de cliente]
      ,[Programacion]
      ,[Actualizacion]
      ,[Fecha creacion toa]

 from [TE101104\PROVISIONSERVER].CCP.dbo.provision_toa
 where Garantía = 'sí' and [Tipo de Acceso] in ('box','EQUIPO IPT','fibra','fibra+iptv','fibra+box','FTTH','iptv')