CREATE TABLE [dbo].[toa_pm_ult31](
	[Técnico] [varchar](100) NULL,
	[ID RECURSO] smallint NULL,
	[Subtipo de Actividad] [varchar](80) NULL,
	[Código de actuación] [varchar](80) NULL,
	[Número de Petición] [varchar](50) NULL,
	[Número de Orden] [varchar](50) NULL,
	[Habilidad del trabajo] [varchar](120) NULL,
	[Empresa] [varchar](50) NULL,
	[Fecha de Emisión/Reclamo] varchar (25) NULL,
	[Segmento del cliente] [varchar](20) NULL,
	[Estado de la orden] [varchar](25) NULL,
	[Pendiente instancia externa] [varchar](80) NULL,
	[Tecnologia Voz] [varchar](20) NULL,
	[Tecnologia Banda Ancha] [varchar](20) NULL,
	[Tecnologia TV] [varchar](20) NULL,
	[Multiproducto] [varchar](50) NULL,
	Tecnologia varchar (100) null,
	[Bucket Inicial] [varchar](80) NULL,
	[Razon de Suspension Instalacion] [varchar](100) NULL,
	[Motivo no realizado instalación] [varchar](150) NULL,
	[Access ID] [varchar](25) NULL,
	Equipos tinyint null,
	Fecha smalldatetime null
)