create table av_garantias_historico (Empresa varchar(50) null,
										Enero float null,
										Febrero float null,
										Marzo float null,
										Abril float null,
										Mayo float null,
										Junio float null,
										Julio float null,
										Agosto float null,
										Septiembre float null,
										Octubre float null,
										Noviembre float null,
										Diciembre float null,
										Anio smallint)