create procedure guardar_cita
@usuario_cita varchar(50),
@fecha_cita date,
@access varchar (25)
as

insert into av_citas ([Fecha gestion cita],
		[Fecha Cita Manual],
		usuario_cita,
		Técnico,
		[ID RECURSO],
		[Subtipo de Actividad],
		[Código de actuación],
		[Número de Petición],
		[Número de Orden],
		Empresa,
		[Fecha de Emisión/Reclamo],
		[Estado de la orden],
		[Categoría de Capacidad],
		[Tecnologia Voz],
		[Tecnologia Banda Ancha],
		[Tecnologia TV],
		Multiproducto,
		[Tipo de Acceso],
		[Tipo Equipo de Acceso],
		Síntoma,
		[Diagnóstico Inicial],
		[Diagnóstico Actual],
		Garantía,
		Central,
		[Nombre Central],
		[Bucket Inicial],
		[Razon de Suspension Instalacion],
		[Motivo no realizado instalación],
		[Comentarios Tecnico],
		[Usuario que autorizo el cierre],
		[Fecha/Hora de autorizacion del cierre],
		[Fecha/Hora de autorizacion de la suspension],
		[Usuario que autorizo la suspension#],
		[Fecha/Hora de autorizacion del quiebre],
		[Usuario que Autoriza Informar],
		[Access ID],
		[Tipo de cliente],
		[Subtipo de cliente],
		[Programacion],
		[Fecha_de_actualizacion],
		[Fecha_de_cumplimiento_insta],
		[Asignacion],
		Averia,
		[Subtipo de Actividad Instalacion],
		[Código de actuación Instalacion],
		[Técnico que instaló],
		[Empresa que instaló],
		[Multiproducto instalado],
		[Tecnología instalada],
		[Fecha creación TOA])

select cast (getdate() as smalldatetime),
		@fecha_cita,
		@usuario_cita,
		[Técnico que instaló],
		[ID RECURSO],
		[Subtipo de Actividad],
		[Código de actuación],
		[Número de Petición],
		[Número de Orden],
		Empresa,
		[Fecha de Emisión/Reclamo],
		[Estado de la orden],
		[Categoría de Capacidad],
		[Tecnologia Voz],
		[Tecnologia Banda Ancha],
		[Tecnologia TV],
		Multiproducto,
		[Tipo de Acceso],
		[Tipo Equipo de Acceso],
		Síntoma,
		[Diagnóstico Inicial],
		[Diagnóstico Actual],
		Garantía,
		Central,
		[Nombre Central],
		[Bucket Inicial],
		[Razon de Suspension Instalacion],
		[Motivo no realizado instalación],
		[Comentarios Tecnico],
		[Usuario que autorizo el cierre],
		[Fecha/Hora de autorizacion del cierre],
		[Fecha/Hora de autorizacion de la suspension],
		[Usuario que autorizo la suspension#],
		[Fecha/Hora de autorizacion del quiebre],
		[Usuario que Autoriza Informar],
		[Access ID],
		[Tipo de cliente],
		[Subtipo de cliente],
		[Programacion],
		[Fecha_de_actualizacion],
		[Fecha_de_cumplimiento_inst],
		[Asignacion],
		Averia,
		[Subtipo de Actividad Instalacion],
		[Código de actuación Instalacion],
		[Técnico que instaló],
		[Empresa que instaló],
		[Multiproducto instalado],
		[Tecnologia instalada],
		[Fecha creación TOA]
		
from av_averias
where [Access ID] = @access