create table mon_aptos (Tipo varchar (10) not null, ARGENCOBRAS tinyint null,
[COMFICA ARGENTINA] tinyint null,
[DOMINION BAIRES SA] tinyint null,
ERB tinyint null,
[GRUPO TECNO MEDANOS] tinyint null,
[ICSRED] tinyint null,
[NG] tinyint null,
[PANAVISION] tinyint null,
[PLANTEL] tinyint null,
[RADIOTRONICA] tinyint null,
RETESAR tinyint null,
TASA tinyint null,
TEAMTEL tinyint null,
[TECN Y CABLEADOS SA] tinyint null,
VALTELLINA tinyint null,
[TASA NEG] tinyint null,
ARGENCOBRA tinyint null)