create table mon_gestionados_contrata (id_gest_ctta int not null primary key identity (1,1),
				red_monitor varchar (40) null,
				fyhgestion smalldatetime not null,
				id_contrata tinyint not null,
				sub_contrata varchar (80) null,
				domicilio varchar (250) null,
				cant_sup tinyint null,
				cant_tec smallint null,
				nom_supervisor varchar (200) null,
				BA_1 tinyint null,
				BA_2 tinyint null,
				BA_3 tinyint null,
				BA_4 tinyint null,
				BA_5 tinyint null,
				BA_6 tinyint null,
				BA_7 tinyint null,
				BA_8 tinyint null,
				BA_9 tinyint null,
				BA_10 tinyint null,
				BA_11 tinyint null,
				BA_12 tinyint null,
				BA_13 tinyint null,
				VOIP_1 tinyint null,
				VOIP_2 tinyint null,
				MP_1 tinyint null,
				MP_2 tinyint null,
				MP_3 tinyint null,
				MP_4 tinyint null,
				MP_5 tinyint null,
				Observaciones varchar (500) null)