create table garantias_descargo (id_descargo int not null primary key identity (1,1),
				id_usuario int not null,
				id_recurso int not null,
				id_empresa tinyint not null,
				nro_peticion varchar (50) not null,
				estado varchar (15) null,
				access_id bigint not null,
				id_central smallint not null,
				subtipo_actividad varchar(200) null,
				fecha_descargo smalldatetime not null,
				fecha_ingreso smalldatetime null,
				fecha_cierre smalldatetime null,
				segmento varchar(11) null,
				tecnologia varchar(12) null,
				comentarios_ctta varchar(500) not null,
				cbo1_ctta tinyint not null,
				cbo2_ctta smallint not null,
				comentarios_gestor varchar(500) null,
				cbo1_gestor tinyint null,
				cbo2_gestor smallint null,
				trabajado_gestor bit not null)