SELECT COUNT(*)
FROM T1000.GPON_EXPRESSE.dbo.REPORTE_ALARMA_IS_OOS
SELECT top 1 *
FROM T1000.GPON_EXPRESSE.dbo.REPORTE_ALARMA_IS_OOS
--ANTIGUO
SELECT top 1 *
FROM T1000.GPON_EXPRESSE.dbo.A_ELIMINAR_REPORTE_ALARMA_IS_OOS

--------------------------------------------------------------------------

SELECT COUNT (*)
FROM T1000.GPON_EXPRESSE.dbo.REPORTE_ALARMA_OOS_IS
SELECT top 1 *
FROM T1000.GPON_EXPRESSE.dbo.REPORTE_ALARMA_OOS_IS

--ANTIGUO
SELECT top 1 *
FROM T1000.GPON_EXPRESSE.dbo.A_ELIMINAR_REPORTE_ALARMA_OOS_IS