create table metricas_ctta (Fecha date,
							id_ctta tinyint,
							metrica_cumplidas decimal(7,6),
							metrica_garantias decimal(7,6),
							metrica_garantias_7d decimal(7,6),
							metrica_monitoreos decimal(7,6),
							metrica_diarias decimal(7,6),
							metrica_citas decimal(7,6),
							metrica_presentismo decimal(7,6),
							tecnologia tinyint)			