create table medallia_encuestas (id_caso int not null identity(1,1) primary key,
								motivo tinyint not null,
								contexto tinyint not null,
								id_clooper smallint not null,
								id_cliente bigint not null,
								id_recurso int not null,
								id_encuesta int not null,
								fecha_encuesta date not null,
								fecha_mail smalldatetime not null,
								fecha_cierre1 smalldatetime null,
								fecha_cierre2 smalldatetime null,
								fecha_cierre3 smalldatetime null,
								nombre varchar(150) null,
								direccion varchar(250) null,
								localidad varchar(150) null,
								contacto varchar(11) null,
								nro_orden varchar(50) null,
								bucket varchar(150) null,
								id_empresa tinyint null,
								nps tinyint null,
								tecnico tinyint null,
								puntualidad tinyint null,
								profesionalidad tinyint null,
								conocimiento tinyint null,
								calidad tinyint null,
								comunicacion tinyint null,
								motivo_detractor tinyint not null,
								concepto tinyint not null,
								subconcepto tinyint null,
								detalle tinyint null,
								accion_ejecutada tinyint not null,
								estado tinyint not null,
								comentarios_cliente varchar(500) null,
								respuesta_cliente tinyint null,
								resp_final_cliente tinyint null,
								respuesta_supervisor varchar(500) null,
								cbo_resp_supervisor tinyint null,
								reiteros tinyint null,
								accion_clooper tinyint null,
								respuesta_clooper varchar(1000) null,
								reagenda bit null,
								access_id bigint null,
								id_gest_clooper tinyint null,
								sn_anterior varchar(80) null,
								sn_actual varchar(80) null,
								segmento varchar(11) null,
								id_central int null)